apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkatopicschemas.dlmiddlecote.io
spec:
  scope: Cluster
  group: dlmiddlecote.io
  names:
    kind: KafkaTopicSchema
    plural: kafkatopicschemas
    singular: kafkatopicschema
    shortNames:
      - kts
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: KeySchemaID
          type: string
          jsonPath: .status.keySchemaID
        - name: ValueSchemaID
          type: string
          jsonPath: .status.valueSchemaID
        - name: Result
          type: string
          jsonPath: .status.result
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
